Fix block() not supported exception in tests
By chance, the exception didn't hinder the tests but it could so fix it

in SecurityAnalysisControllerTest#runAndSaveTest
15:51:19.038 [parallel-8] ERROR org.gridsuite.securityanalysis.server.service.SecurityAnalysisWorkerService - Exception in consumeRun
java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-8
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
	at reactor.core.publisher.Mono.block(Mono.java:1707)
	at org.gridsuite.securityanalysis.server.service.SecurityAnalysisWorkerService.lambda$consumeRun$14(SecurityAnalysisWorkerService.java:296)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeConsumer(SimpleFunctionRegistry.java:987)